name: scribbly-dev

services:
  auth-service:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/auth/node_modules
      - /app/packages/common/node_modules
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    depends_on:
      pg-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - '${AUTH_SERVICE_PORT}:4000'
    env_file:
      - .env

  user-service:
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/user/node_modules
      - /app/packages/common/node_modules
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    depends_on:
      pg-db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    ports:
      - '${USER_SERVICE_PORT}:4001'
    env_file:
      - .env

  post-service:
    env_file:
      - .env
    ports:
      - '${POST_SERVICE_PORT}:4002'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/post/node_modules
      - /app/packages/common/node_modules
    build:
      context: .
      dockerfile: ./services/post/Dockerfile
    depends_on:
      - mongo-db

  web:
    env_file:
      - .env
    environment:
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    ports:
      - '${WEB_PORT}:3000'
    volumes:
      - .:/app
      - /app/node_modules
      - /app/services/web/node_modules
      - /app/packages/common/node_modules
    build:
      context: .
      dockerfile: ./services/web/Dockerfile

  pg-db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres-data:/var/lib/postgresql
    ports:
      - '${PG_PORT}:5432'

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - '${RABBITMQ_PORT}:5672'
      - '${RABBITMQ_MGMT_PORT}:15672'
    healthcheck:
      test: ['CMD', 'rabbitmq-diagnostics', '-q', 'ping']

  mongo-db:
    image: mongo # no alpine image 🙁
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes

  nginx:
    env_file:
      - .env
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx
    volumes:
      - ./services/nginx:/etc/nginx/templates:ro
    ports:
      - '80:80'
    depends_on:
      - auth-service
      - user-service
      - post-service
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile

volumes:
  postgres-data:
  mongo-data:
  redis-data:
