packages:
  - 'services/*'
  - 'packages/*'
confirmModulesPurge: false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
trustLockfile: true
dangerouslyAllowAllBuilds: true
injectWorkspacePackages: true
