FROM node:lts-alpine AS build
RUN corepack enable
WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY packages/common/package.json ./packages/common/
COPY services/user/package.json ./services/user/

RUN --mount=type=cache,id=pnpm,target=/app/.pnpm-store \
    pnpm config set store-dir /app/.pnpm-store && \
    pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter user... run build
RUN pnpm -F user deploy --prod --legacy /prod/user


FROM node:lts-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /prod/user ./
CMD ["node", ".dist/index.mjs"]
