FROM node:lts-alpine AS build
ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

RUN corepack enable
WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY packages/common/package.json ./packages/common/
COPY services/web/package.json ./services/web/

RUN --mount=type=cache,id=pnpm,target=/app/.pnpm-store \
    pnpm config set store-dir /app/.pnpm-store && \
    pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter web... run build
RUN pnpm -F web deploy --prod --legacy /prod/web


FROM node:lts-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /prod/web ./
COPY --from=build /app/services/web/.next ./.next
COPY --from=build /app/services/web/public ./public
CMD ["node", "node_modules/next/dist/bin/next", "start"]
